### ISSUE TITLE
Issue with sessionduration since latest v3.1. Extension is not working

### ISSUE THREAD

**Issue by shubhkb** [prolane/samltoawsstskeys#62] opened 2022-12-19 07:00 UTC
There is an issue in latest version 3.1, in `script.js` file inside `onBeforeRequestEvent` function `sessionduration` is not defined because of that it is not working please fix this asap.

```
let sessionduration = undefined;
```

<img width="589" alt="image" src="https://user-images.githubusercontent.com/49670449/208366433-998e8791-a685-41f3-8d45-0ef5548f918d.png">

**Comment by prolane** [comment] 2022-12-19 08:01
Hi @shubhkb 
The line you are referring to is just the declaration of the variable.

Could you post the debug logs here?
See https://github.com/prolane/samltoawsstskeys#faq-frequently-asked-question for help.

**Comment by mimol91** [comment] 2022-12-19 10:05
<img width="629" alt="Screen Shot 2022-12-19 at 14 03 59" src="https://user-images.githubusercontent.com/2659069/208400251-5bd1c573-10a9-477a-83e3-7b4b1bb6a363.png">


<img width="921" alt="Screen Shot 2022-12-19 at 14 05 11" src="https://user-images.githubusercontent.com/2659069/208400299-f0926bb7-c3fa-4cc7-b074-4ef101863eef.png">

**Comment by Bobatron** [comment] 2022-12-19 11:46
I have been having this same issue since last Friday: 
![image](https://user-images.githubusercontent.com/40393265/208418934-531efd9e-dcd4-425f-be4a-a064b5b36660.png)

Whilst this is being fixed, a workaround to getting the credentials file to downloaded is:

1. View the extension settings via the 'Manage Extension' option
2. Enable developer mode:
![image](https://user-images.githubusercontent.com/40393265/208418003-594be495-1133-4e55-869d-3101e300990b.png)
3. Inspect the service worker view: 
![image](https://user-images.githubusercontent.com/40393265/208418227-f4247e51-9b2b-4a8f-9f05-3206fdc5438b.png)
4. From the console, set the value for sessionduration: 
![image](https://user-images.githubusercontent.com/40393265/208418514-3b15ca2a-f20f-4a07-acc6-1515c91f28e5.png)
5. Connect to AWS and the credentials file should download as expected

**Comment by shubhkb** [comment] 2022-12-19 11:48
> Hi @shubhkb The line you are referring to is just the declaration of the variable.
> 
> Could you post the debug logs here? See https://github.com/prolane/samltoawsstskeys#faq-frequently-asked-question for help.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/49670449/208419226-f166941d-28e0-4d22-8db2-3b551e65a2c1.png">

**Comment by prolane** [comment] 2022-12-19 19:11
With the refactoring of the code due to Chrome Extension manifest V3 there was indeed a bug introduced related to the `sessionduration`. I was able to reproduce the issue. You'll encounter this issue when your IDP does not add a Session Duration as one of the SAML Assertion attributes.

This is now fixed with this:
https://github.com/prolane/samltoawsstskeys/blob/86a2c87b8bd2c680166b5da553b6e616967e1bfc/background/script.js#L143

I'll publish v3.2 tonight in the Chrome web store.

Please let me know if this indeed fixed it for you.

**Comment by prolane** [comment] 2022-12-20 07:41
@shubhkb I agree with you I should declare the variable in a next updated version and I will. For now I don't think it will make any functional difference, does it? The `sessionduration` variable will implicitly be a global variable due to:
https://github.com/prolane/samltoawsstskeys/blob/86a2c87b8bd2c680166b5da553b6e616967e1bfc/background/script.js#L116

If your IDP does not include the SessionDuration Attribute, the `sessionduration` will be typeof 'undefined' as now checked on that line `143` where the error occurred.
https://github.com/prolane/samltoawsstskeys/blob/86a2c87b8bd2c680166b5da553b6e616967e1bfc/background/script.js#L143

**Comment by prolane** [comment] 2023-03-22 07:27
Closing this issue as this has been resolved and no new comments haven been left here.

**Closed by prolane** 2023-03-22 07:27 UTC
