### ISSUE TITLE
Chrome 62 breaks extension

### ISSUE THREAD

**Issue by bdruth** [prolane/samltoawsstskeys#6] opened 2017-10-24 13:30 UTC
In Chrome 62, the extension no longer downloads a credentials file. Worked in Chrome 61 just fine.

(sorry for dupe, posted this previously under the wrong account (service account)).

**Comment by prolane** [comment] 2017-10-31 21:48
@bdruth Thanks for reporting. Could you post the console output when the error occurs?

I wrote the Chrome extension while I was at my former employer. Currently I am at a company which does not have sso using saml2 set up for AWS. Therefore I'm not able to test myself at the moment. I'm going to work on a private setup with my own saml2 idp, but this won't be on short notice.

Since you specifically pointed out the **formData** object is not available anymore in Chrome 62 I did do a little test, exactly as suggested in one of the replies the Chromium bug report which you filed. (https://bugs.chromium.org/p/chromium/issues/detail?id=777898#c6)

I am running Chrome 62.0.3202.75 on MacOS. **formData** is actually still available for me. Could you do the same test?

1. Download this simple extension (based on the one from phistuck)
[webrequest-test-extension.zip](https://github.com/prolane/samltoawsstskeys/files/1432383/webrequest-test-extension.zip)
2. unzip
3. Open the extension page in Chrome. Turn on *Developer mode* using the checkbox.
4. Hit the button to *Load unpacked extension*. Select the directory of the unzipped extension.
5. The *WebRequest Tester* extension will show. Click *background page*. This should open a new window showing the console output of the background process of this test extension.
6. In a new Chrome tab open: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_form_post
7. Hit the *Submit* button of the form.
8. Check the console output in the separate window. It should show you the complete **formData** object plus one line showing '*First Name: Mickey*'.

Let me know if it works for you.

P.S.
When testing the Chrome extension for AWS, please open the background page as well to inspect the console output of the background process.

**Comment by prolane** [comment] 2017-11-01 07:28
Issue has been confirmed. Interestingly enough **formData** is still available in Chrome 62 for users who reported the issue for this extension. The above example with the *webrequest-test-extension* should show the **formData** just fine. So I expect something else is failing in the AWS STS extension, but I'll have to debug that somewhere in the future once I have my IDP set up.

I'll do a quick check on the code and make sure the extension is updated in the Chrome web store.

**Comment by prolane** [comment] 2017-11-03 15:12
[gbvanrenswoude](https://gitlab.com/gbvanrenswoude) confirmed extension is now working properly again.

@bdruth It should work for you as well now. Please let me know if you experience any other issues, but I'll close this issue.

**Closed by prolane** 2017-11-03 15:12 UTC

**Comment by etendards** [comment] 2017-12-11 18:43
We are using Okta.  I do not see a file being written after a successful Okta AWS login.
